const w1 = [
    [
        ["ich habe gearbeitet", "ɪç ˈhaːbə ɡəˈaɐ̯ˌbaɪ̯tət", "я работал"],
        ["du hast gearbeitet", "du ˈhast ɡəˈaɐ̯ˌbaɪ̯tət", "ты работал"],
        ["er hat gearbeitet", "eːɐ̯ ˈhat ɡəˈaɐ̯ˌbaɪ̯tət", "он работал"],
        ["sie hat gearbeitet", "ziː ˈhat ɡəˈaɐ̯ˌbaɪ̯tət", "она работала"],
        ["es hat gearbeitet", "ɛs ˈhat ɡəˈaɐ̯ˌbaɪ̯tət", "оно работало"],
        ["wir haben gearbeitet", "vɪʁ ˈhaːbn̩ ɡəˈaɐ̯ˌbaɪ̯tət", "мы работали"],
        ["ihr habt gearbeitet", "iːɐ̯ ˈhabt ɡəˈaɐ̯ˌbaɪ̯tət", "вы работали"],
        ["sie haben gearbeitet", "ziː ˈhabən ɡəˈaɐ̯ˌbaɪ̯tət", "они работали"],
 
        ["ich habe zugehört", "ɪç ˈhaːbə t͡suˈɡəˌhœʁt", "я слушал"],
        ["du hast zugehört", "du ˈhast t͡suˈɡəˌhœʁt", "ты слушал"],
        ["er hat zugehört", "eːɐ̯ ˈhat t͡suˈɡəˌhœʁt", "он слушал"],
        ["sie hat zugehört", "ziː ˈhat t͡suˈɡəˌhœʁt", "она слушала"],
        ["es hat zugehört", "ɛs ˈhat t͡suˈɡəˌhœʁt", "оно слушало"],
        ["wir haben zugehört", "vɪʁ ˈhaːbn̩ t͡suˈɡəˌhœʁt", "мы слушали"],
        ["ihr habt zugehört", "iːɐ̯ ˈhabt t͡suˈɡəˌhœʁt", "вы слушали"],
        ["sie haben zugehört", "ziː ˈhabən t͡suˈɡəˌhœʁt", "они слушали"],
    
        ["ich habe geantwortet", "ɪç ˈhaːbə ɡəˈantvɔʁtət", "я отвечал"],
        ["du hast geantwortet", "du ˈhast ɡəˈantvɔʁtət", "ты отвечал"],
        ["er hat geantwortet", "eːɐ̯ ˈhat ɡəˈantvɔʁtət", "он отвечал"],
        ["sie hat geantwortet", "ziː ˈhat ɡəˈantvɔʁtət", "она отвечала"],
        ["es hat geantwortet", "ɛs ˈhat ɡəˈantvɔʁtət", "оно отвечало"],
        ["wir haben geantwortet", "vɪʁ ˈhaːbn̩ ɡəˈantvɔʁtət", "мы отвечали"],
        ["ihr habt geantwortet", "iːɐ̯ ˈhabt ɡəˈantvɔʁtət", "вы отвечали"],
        ["sie haben geantwortet", "ziː ˈhabən ɡəˈantvɔʁtət", "они отвечали"],
   
        ["ich habe gelebt", "ɪç ˈhaːbə ɡəˈleːbt", "я жил"],
        ["du hast gelebt", "du ˈhast ɡəˈleːbt", "ты жил"],
        ["er hat gelebt", "eːɐ̯ ˈhat ɡəˈleːbt", "он жил"],
        ["sie hat gelebt", "ziː ˈhat ɡəˈleːbt", "она жила"],
        ["es hat gelebt", "ɛs ˈhat ɡəˈleːbt", "оно жило"],
        ["wir haben gelebt", "vɪʁ ˈhaːbn̩ ɡəˈleːbt", "мы жили"],
        ["ihr habt gelebt", "iːɐ̯ ˈhabt ɡəˈleːbt", "вы жили"],
        ["sie haben gelebt", "ziː ˈhabən ɡəˈleːbt", "они жили"],
    
        ["ich habe gefragt", "ɪç ˈhaːbə ɡəˈfʁaːɡt", "я спрашивал"],
        ["du hast gefragt", "du ˈhast ɡəˈfʁaːɡt", "ты спрашивал"],
        ["er hat gefragt", "eːɐ̯ ˈhat ɡəˈfʁaːɡt", "он спрашивал"],
        ["sie hat gefragt", "ziː ˈhat ɡəˈfʁaːɡt", "она спрашивала"],
        ["es hat gefragt", "ɛs ˈhat ɡəˈfʁaːɡt", "оно спрашивало"],
        ["wir haben gefragt", "vɪʁ ˈhaːbn̩ ɡəˈfʁaːɡt", "мы спрашивали"],
        ["ihr habt gefragt", "iːɐ̯ ˈhabt ɡəˈfʁaːɡt", "вы спрашивали"],
        ["sie haben gefragt", "ziː ˈhabən ɡəˈfʁaːɡt", "они спрашивали"],
 
        ["ich habe gemacht", "ɪç ˈhaːbə ɡəˈmaχt", "я делал"],
        ["du hast gemacht", "du ˈhast ɡəˈmaχt", "ты делал"],
        ["er hat gemacht", "eːɐ̯ ˈhat ɡəˈmaχt", "он делал"],
        ["sie hat gemacht", "ziː ˈhat ɡəˈmaχt", "она делала"],
        ["es hat gemacht", "ɛs ˈhat ɡəˈmaχt", "оно делало"],
        ["wir haben gemacht", "vɪʁ ˈhaːbn̩ ɡəˈmaχt", "мы делали"],
        ["ihr habt gemacht", "iːɐ̯ ˈhabt ɡəˈmaχt", "вы делали"],
        ["sie haben gemacht", "ziː ˈhabən ɡəˈmaχt", "они делали"],
     
    ["ich habe getrunken", "ɪç ˈhaːbə ɡəˈtʁʊŋkən", "я пил"],
    ["du hast getrunken", "du ˈhast ɡəˈtʁʊŋkən", "ты пил"],
    ["er hat getrunken", "eːɐ̯ ˈhat ɡəˈtʁʊŋkən", "он пил"],
    ["sie hat getrunken", "ziː ˈhat ɡəˈtʁʊŋkən", "она пила"],
    ["es hat getrunken", "ɛs ˈhat ɡəˈtʁʊŋkən", "оно пило"],
    ["wir haben getrunken", "vɪʁ ˈhaːbn̩ ɡəˈtʁʊŋkən", "мы пили"],
    ["ihr habt getrunken", "iːɐ̯ ˈhabt ɡəˈtʁʊŋkən", "вы пили"],
    ["sie haben getrunken", "ziː ˈhabən ɡəˈtʁʊŋkən", "они пили"],

        ["ich habe gewollt", "ɪç ˈhaːbə ɡəˈvɔlt", "я хотел"],
        ["du hast gewollt", "du ˈhast ɡəˈvɔlt", "ты хотел"],
        ["er hat gewollt", "eːɐ̯ ˈhat ɡəˈvɔlt", "он хотел"],
        ["sie hat gewollt", "ziː ˈhat ɡəˈvɔlt", "она хотела"],
        ["es hat gewollt", "ɛs ˈhat ɡəˈvɔlt", "оно хотело"],
        ["wir haben gewollt", "vɪʁ ˈhaːbn̩ ɡəˈvɔlt", "мы хотели"],
        ["ihr habt gewollt", "iːɐ̯ ˈhabt ɡəˈvɔlt", "вы хотели"],
        ["sie haben gewollt", "ziː ˈhabən ɡəˈvɔlt", "они хотели"],
       
            ["ich habe verstanden", "ɪç ˈhaːbə fɛɐ̯ˈʃtandən", "я понимал"],
            ["du hast verstanden", "du ˈhast fɛɐ̯ˈʃtandən", "ты понимал"],
            ["er hat verstanden", "eːɐ̯ ˈhat fɛɐ̯ˈʃtandən", "он понимал"],
            ["sie hat verstanden", "ziː ˈhat fɛɐ̯ˈʃtandən", "она понимала"],
            ["es hat verstanden", "ɛs ˈhat fɛɐ̯ˈʃtandən", "оно понимало"],
            ["wir haben verstanden", "vɪʁ ˈhaːbn̩ fɛɐ̯ˈʃtandən", "мы понимали"],
            ["ihr habt verstanden", "iːɐ̯ ˈhabt fɛɐ̯ˈʃtandən", "вы понимали"],
            ["sie haben verstanden", "ziː ˈhabən fɛɐ̯ˈʃtandən", "они понимали"],
        
                ["ich habe gewollt", "ɪç ˈhaːbə ɡəˈvɔlt", "я хотел"],
                ["du hast gewollt", "du ˈhast ɡəˈvɔlt", "ты хотел"],
                ["er hat gewollt", "eːɐ̯ ˈhat ɡəˈvɔlt", "он хотел"],
                ["sie hat gewollt", "ziː ˈhat ɡəˈvɔlt", "она хотела"],
                ["es hat gewollt", "ɛs ˈhat ɡəˈvɔlt", "оно хотело"],
                ["wir haben gewollt", "vɪʁ ˈhaːbn̩ ɡəˈvɔlt", "мы хотели"],
                ["ihr habt gewollt", "iːɐ̯ ˈhabt ɡəˈvɔlt", "вы хотели"],
                ["sie haben gewollt", "ziː ˈhabən ɡəˈvɔlt", "они хотели"],
                ],
                [
                ["ich habe gekauft", "ɪç ˈhaːbə ɡəˈkaʊft", "я покупал"],
                ["du hast gekauft", "du ˈhast ɡəˈkaʊft", "ты покупал"],
                ["er hat gekauft", "eːɐ̯ ˈhat ɡəˈkaʊft", "он покупал"],
                ["sie hat gekauft", "ziː ˈhat ɡəˈkaʊft", "она покупала"],
                ["es hat gekauft", "ɛs ˈhat ɡəˈkaʊft", "оно покупало"],
                ["wir haben gekauft", "vɪʁ ˈhaːbn̩ ɡəˈkaʊft", "мы покупали"],
                ["ihr habt gekauft", "iːɐ̯ ˈhabt ɡəˈkaʊft", "вы покупали"],
                ["sie haben gekauft", "ziː ˈhabən ɡəˈkaʊft", "они покупали"],
              
                ["ich habe gefühlt", "ɪç ˈhaːbə ɡəˈfʏlt", "я чувствовал"],
                ["du hast gefühlt", "du ˈhast ɡəˈfʏlt", "ты чувствовал"],
                ["er hat gefühlt", "eːɐ̯ ˈhat ɡəˈfʏlt", "он чувствовал"],
                ["sie hat gefühlt", "ziː ˈhat ɡəˈfʏlt", "она чувствовала"],
                ["es hat gefühlt", "ɛs ˈhat ɡəˈfʏlt", "оно чувствовало"],
                ["wir haben gefühlt", "vɪʁ ˈhaːbn̩ ɡəˈfʏlt", "мы чувствовали"],
                ["ihr habt gefühlt", "iːɐ̯ ˈhabt ɡəˈfʏlt", "вы чувствовали"],
                ["sie haben gefühlt", "ziː ˈhabən ɡəˈfʏlt", "они чувствовали"],
              
                ["mir hat es gefallen", "miːɐ̯ hat ɛs ɡəˈfalən", "мне понравилось"],
                ["dir hat es gefallen", "diːɐ̯ hat ɛs ɡəˈfalən", "тебе понравилось"],
                ["ihm hat es gefallen", "ɪm hat ɛs ɡəˈfalən", "ему понравилось"],
                ["ihr hat es gefallen", "iːɐ̯ hat ɛs ɡəˈfalən", "ей понравилось"],
                ["uns hat es gefallen", "ʊns hat ɛs ɡəˈfalən", "нам понравилось"],
                ["euch hat es gefallen", "ɔɪ̯ç hat ɛs ɡəˈfalən", "вам понравилось"],
                ["ihnen hat es gefallen", "ˈɪmn̩ hat ɛs ɡəˈfalən", "им понравилось"],
                ]




]

export default w1