const w1 = [
  [
    ["Ich gucke oft fern.", "[ɪç ˈɡʊkə ʊft fɛʁn]", "Я часто смотрю телевизор.", ""],
    ["Hältst du das?", "[hɛlst du das?]", "Ты это держишь?", ""],
    ["Lass mich in Ruhe!", "[las mɪç ɪn ˈʁuːə!]", "Оставь меня в покое!", ""],
    ["Hast du das bemerkt?", "[hast du das bəˈmɛʁkt?]", "Ты это заметил?", ""],
    ["Wir reden über alles.", "[viːʁ ˈʁeːdn̩ ˈyːbɐ ˈaləs]", "Мы разговариваем обо всем.", ""],
    ["Kannst du das sehen?", "[kʰanst du das ˈzeːən?]", "Ты это видишь?", ""],
    ["Er will hingucken, aber er zögert.", "[ɛʁ vɪl ˈhɪŋˌʔʊkən, ˈabɐ ɛʁ ˈt͡søːɡɐt]", "Он хочет посмотреть, но он колеблется.", ""],
    ["Erinnerst du dich an unseren letzten Urlaub?", "[ɛˈʁɪnɐst du dɪç an ˈʊnzeʁən ˈlɛtstən ˈʊʁlaʊ̯p?]", "Ты помнишь наш последний отпуск?", ""],
    ["Ich gebe dir das Buch.", "[ɪç ˈɡeːbə diːɐ das bʊx]", "Я даю тебе книгу.", ""],
    ["Er hat seinen Schlüssel verloren.", "[ɛʁ hat ˈzaɪ̯nən ˈʃlʏsəl fɛʁˈlɪʁən]", "Он потерял свой ключ.", ""],
    ["Ich versuche es zu verstehen.", "[ɪç fɛʁˈzuːxə ɛs tsuː fɛʁˈʃteːən]", "Я пытаюсь понять это.", ""],
    ["Ich vertraue dir.", "[ɪç fɛʁˈtʁaʊ̯ə diːɐ]", "Я тебе доверяю.", ""],
    ["Erzähl mir mehr!", "[ɛʁˈt͡seːl mɪʁ meːɐ]", "Расскажи мне больше!", ""],
    ["Ich denke, das ist richtig.", "[ɪç ˈdɛŋkə das ɪst ˈʁɪçtɪç]", "Я думаю, что это правильно.", ""],
    ["Hast du vergessen, was du gesagt hast?", "[hast du fɛʁˈɡɛsən vas du ɡəˈzaːkt hast?]", "Ты забыл, что сказал?", ""],
    ["Weißt du, wie spät es ist?", "[vaɪ̯st du viː ʃpɛːt ɛs ɪst?]", "Ты знаешь, который час?", ""],
    ["Ich schlafe gerne.", "[ɪç ˈʃlaːfə ˈɡɛʁnə]", "Я люблю спать.", ""],
    ["Ich wache jeden Morgen um 7 Uhr auf.", "[ɪç ˈvaχə ˈjeːdn̩ ˈmɔʁɡn̩ ʊm ˈziːbn̩ ʊːɐ aʊ̯f]", "Я просыпаюсь каждое утро в 7 часов.", ""],
    ["Er hört nie auf zu arbeiten.", "[ɛʁ hœʁt niː aʊ̯f tsuː ˈaʁbaɪ̯tn̩]", "Он никогда не прекращает работать.", ""],
    ["Er lügt ständig.", "[ɛʁ lʏːɡt ˈʃtɛndɪç]", "Он постоянно лжет.", ""],
    ["Guck mal!", "[ɡʊk mal]", "Посмотри!", ""],
    ["Wir gucken uns einen Film an.", "[viːɐ̯ ˈɡʊkən ʊns ˈaɪ̯nən fɪlm an]", "Мы смотрим фильм.", ""],
    ["Warum guckst du so?", "[ˈvaːʁʊm ˈɡʊkst du zoː]", "Почему ты так смотришь?", ""],
    ["Er guckt durch das Fenster.", "[ɛʁ ˈɡʊkt dʊʁç das ˈfɛnstɐ]", "Он смотрит через окно.", ""],
    ["Ich habe es bemerkt.", "[bəˈmɛʁkən]", "замечать", ""],
    ["Hast du das gesehen?", "[ˈɡʊkən]", "смотреть", ""],
    ["Er hielt das Glas fest.", "[ˈhaltən]", "держать", ""],
    ["Er lässt mich in Ruhe.", "[ˈlasən]", "оставлять, позволять", ""],
    ["Wir haben über alles geredet.", "[ˈʁeːdn̩]", "разговаривать", ""],
    ["Hast du ihn gesehen?", "[ɡəˈzeːən]", "видеть", ""],
    ["Schau mal da hin!", "[ˈhɪŋˌʔʊkən]", "смотреть", ""],
    ["Er erinnerte mich daran.", "[ɛˈʁɪnəʁn]", "напоминать", ""],
    ["Er gab mir das Buch.", "[ˈɡeːbn̩]", "давать", ""],
    ["Ich habe meinen Schlüssel verloren.", "[fɛʁˈlɪʁən]", "терять", ""],
    ["Er versuchte es noch einmal.", "[fɛʁˈzuːxən]", "пытаться", ""],
    ["Ich vertraue ihm.", "[fɛʁˈtʁaʊ̯ən]", "доверять", ""],
    ["Sie erzählte mir eine Geschichte.", "[ɛʁˈt͡seːlən]", "рассказывать", ""],
    ["Ich dachte, es wäre besser.", "[ˈdɛŋkən]", "думать", ""],
    ["Ich habe das vergessen.", "[fɛʁˈɡɛsən]", "забывать", ""],
    ["Weißt du das?", "[ˈvɪsən]", "знать", ""],
    ["Er hat tief geschlafen.", "[ˈʃlaːfn̩]", "спать", ""],
    ["Ich wachte früh auf.", "[ˈaʊ̯fˌvaχən]", "просыпаться", ""],
    ["Sie hörte auf zu arbeiten.", "[ˈaʊ̯fˌhøːʁən]", "прекращать", ""],
    ["Er hat gelogen.", "[ˈlyːɡən]", "лгать", ""],
    ["Hast du das gesehen?", "[ˈɡʊkən]", "смотреть", ""],
    ["Das war nur bedingt richtig.", "[bəˈdɪŋt]", "условно", ""],
    ["Das war ein ständiges Problem.", "[ˈʃtɛndlɪç]", "постоянный", ""],

    ["gucken", "[ˈɡʊkən]", "смотреть", ""],
    ["halten", "[ˈhaltən]", "держать", ""],
    ["lassen", "[ˈlasən]", "оставлять, позволять", ""],
    ["bemerken", "[bəˈmɛʁkən]", "замечать", ""],
    ["reden", "[ˈʁeːdn̩]", "разговаривать", ""],
    ["sehen", "[ɡəˈzeːən]", "видеть", ""],
    ["hingucken", "[ˈhɪŋˌʔʊkən]", "смотреть", ""],
    ["erinnern", "[ɛˈʁɪnəʁn]", "напоминать", ""],
    ["geben", "[ˈɡeːbn̩]", "давать", ""],
    ["verlieren", "[fɛʁˈlɪʁən]", "терять", ""],
    ["versuchen", "[fɛʁˈzuːxən]", "пытаться", ""],
    ["vertrauen", "[fɛʁˈtʁaʊ̯ən]", "доверять", ""],
    ["erzählen", "[ɛʁˈt͡seːlən]", "рассказывать", ""],
    ["denken", "[ˈdɛŋkən]", "думать", ""],
    ["vergessen", "[fɛʁˈɡɛsən]", "забывать", ""],
    ["wissen", "[ˈvɪsən]", "знать", ""],
    ["schlafen", "[ˈʃlaːfn̩]", "спать", ""],
    ["aufwachen", "[ˈaʊ̯fˌvaχən]", "просыпаться", ""],
    ["aufhören", "[ˈaʊ̯fˌhøːʁən]", "прекращать", ""],
    ["lügen", "[ˈlyːɡən]", "лгать", ""],
    ["gucken", "[ˈɡʊkən]", "смотреть", ""],
    ["bedingt", "[bəˈdɪŋt]", "условно", ""],
    ["halten", "[ˈhaltən]", "держать", ""],
    ["ständlich", "[ˈʃtɛndlɪç]", "постоянный", ""],

    ["lassen", "[ˈlasən]", "оставлять, позволять", ""],
    ["Stich", "[ʃtɪç]", "укол, укус", ""],
    ["Sprüche", "[ˈʃprʏçə]", "изречения, фразы", ""],
    ["Versuch", "[fɛɐ̯ˈzuːx]", "попытка, эксперимент", ""],
    ["geschlossen", "[ɡəˈʃlɔsən]", "закрытый", ""],
    ["denn", "[dɛn]", "потому что", ""],
    ["etwas", "[ˈɛtvɑs]", "что-то", ""],
    ["ganze", "[ˈɡant͡sə]", "целый", ""],
    ["Zeit", "[tsaɪ̯t]", "время", ""],
    ["vorbei", "[fɔʁˈbaɪ̯]", "мимо", ""],
    ["glaube", "[ˈɡlaʊbə]", "верю", ""],
    ["einfach", "[ˈaɪ̯nfaχ]", "простой", ""],
    ["nur", "[nuːɐ]", "только", ""],
    ["weggeguckt", "[ˈvɛkɡəˌkʊkt]", "отведенный взгляд", ""],
    ["entscheidenden", "[ɛntˈʃaɪ̯dən̩dən]", "решающий", ""],
    ["Unterschied", "[ˈʊntɐʃiːt]", "различие", ""],
    ["zwischen", "[ˈt͡svɪʃən]", "между", ""],
    ["hingucken", "[ˈhɪŋˌʔʊkən]", "смотреть", ""],
    ["Ich neige dazu", "[ɪç ˈnaɪ̯ɡə daˈtsuː]", "Я склонен", ""],
    ["neige", "[ˈnaɪ̯ɡə]", "склоняться", ""],
    ["dazu", "[daˈtsuː]", "к этому", ""],
    ["solche", "[ˈzɔlçə]", "такие", ""],
    ["Dinge", "[ˈdɪŋə]", "вещи", ""],
    ["bemerken", "[bəˈmɛʁkən]", "замечать", ""],
    ["sicher", "[ˈzɪçɐ]", "уверенный", ""],
    ["ich sicher", "[ɪç ˈzɪçɐ]", "я уверен", ""],
    ["glaube", "[ˈɡlaʊbə]", "верю", ""],
    ["Sie", "[ziː]", "вы", ""],
    ["gewisser", "[ɡəˈvɪsɐ]", "определенный", ""],
    ["Weise", "[ˈvaɪ̯zə]", "способ", ""],
    ["erinnere", "[ɛˈʁɪnəʁə]", "напоминаю", ""],
    ["unbedingt", "[ˈʊnbədɪŋt]", "обязательно", ""],
    ["Reden", "[ˈʁeːdn̩]", "разговаривать", ""],
    ["gesehen", "[ɡəˈzeːən]", "видел", ""],
    ["Niemand", "[ˈniːmand]", "никто", ""],
    ["ihn", "[iːn]", "его", ""],
    ["eingeschlossen", "[ˈaɪ̯nɡəˌʃlɔsən]", "заперся", ""],
    ["träumt", "[tʁɔʏmt]", "мечтает", ""],
    ["Geben", "[ˈɡeːbn̩]", "давать", ""],
    ["Schuld", "[ʃʊlt]", "вина", ""],
    ["über", "[ˈyːbɐ]", "о", ""],
    ["nach", "[naχ]", "после", ""],
    ["über ihn nach", "[ˈyːbɐ iːn naχ]", "размышлять о нем", ""],
    ["versucht", "[fɛɐˈzuːxt]", "пытался", ""],
    ["aufzunehmen", "[ˈaʊfˌtsuːˌneːmən]", "взять на заметку", ""],
    ["Erzählen", "[ɛʁˈt͡seːlən]", "рассказывать"],
    ["Vormittag", "[ˈfɔʁˌmɪtaːk]", "утро"],
    ["Anfang", "[ˈanfʊŋ]", "начало"],
    ["aufwachen", "[ˈaʊ̯fˌvaχən]", "просыпаться"],
    ["schlafen", "[ˈʃlaːfn̩]", "спать"],
    ["gar nicht", "[ɡaːɐ̯ nɪçt]", "совсем не"],
    ["aufhören", "[ˈaʊ̯fˌhøːʁən]", "прекращать"],
    ["liegen", "[ˈliːɡn̩]", "лежать"],
    ["allein", "[aˈlaɪ̯n]", "один"],
    ["Bett", "[bɛt]", "кровать"],
    ["meinen", "[ˈmaɪ̯nən]", "иметь в виду"],
    ["Tochter", "[ˈtɔχtɐ]", "дочь"],
    ["Freunde", "[ˈfʁɔʏndə]", "друзья"],
    ["aushalten", "[ˈaʊ̯shaltən]", "выдерживать"],
    ["letzte", "[ˈlɛt͡stʏ]", "последний"],
    ["Nacht", "[naχt]", "ночь"],
    ["verständlich", "[fɛʁˈʃtɛntlɪç]", "понятно"],
    ["müssen", "[ˈmʏsən]", "должен"],
    ["inakzeptabel", "[ɪnaksɛpˈtaːbl̩]", "неприемлемый"],
    ["aussprechen", "[ˈaʊ̯sˌpʁɛçən]", "говорить вслух"],
    ["in Ordnung", "[ɪn ˈɔʁdnʊŋ]", "в порядке"],
    ["im Stich lassen", "[ɪm ˈʃtɪç ˈlasən]", "оставить в беде"],
    ["verlieren", "[fɛʁˈlɪʁən]", "терять"],
    ["Ansprüche", "[ˈanˌʃpʁʏxə]", "требования"],
    ["versuchen", "[fɛʁˈzuːxən]", "пытаться"],
    ["vertrauen", "[fɛʁˈtʁaʊ̯ən]", "доверять"],
    ["neue", "[ˈnɔʏə]", "новый"],
    ["erzählen", "[ɛʁˈt͡seːlən]", "рассказывать"],
    ["warum", "[vaˈʁʊm]", "почему"],
    ["nicht können", "[nɪçt ˈkœnən]", "не мочь"],
    ["geht", "[ɡeːt]", "можно"],
    ["denken", "[ˈdɛŋkən]", "думать"],
    ["wichtig", "[ˈvɪçtɪç]", "важно"],
    ["vergessen", "[fɛʁˈɡɛsən]", "забывать"],
    ["real", "[ʁeˈaːl]", "реально"],
    ["sehen", "[ˈzeːən]", "видеть"],
    ["dort", "[dɔʁt]", "там"],
    ["wissen", "[ˈvɪsən]", "знать"],
    ["versuchen", "[fɛʁˈzuːxən]", "пытаться"],
    ["liebe", "[ˈliːbə]", "любовь"],
    ["später", "[ˈʃpɛːtɐ]", "позже"],
    ["geben", "[ˈɡeːbn̩]", "давать"],
    ["nicht erzählen", "[nɪçt ɛʁˈt͡seːlən]", "не рассказывать"]
  ],


  [
    ["Wer", "vɛr", "Кто"],
    ["Was", "vas", "Что"],
    ["Wann", "van", "Когда"],
    ["Wo", "voː", "Где"],
    ["Woher", "voːhɛr", "Откуда"],
    ["Wohin", "voːhɪn", "Куда"],
    ["Wie", "viː", "Как"],
    ["Warum", "vaˈʁʊm", "Почему"],
    ["Wieso", "ˈviːzo", "Почему"],
    ["Weshalb", "ˈveːʃalp", "Почему"],
    ["Welcher", "ˈvɛlxɐ,", "Какой"],
    ["Wozu", "", "зачем"],
    ["Wem", "", "кому"],

  ],

  [   
    ["Ein", "aɪ̯n", "Один"],
    ["kleiner", "ˈklaɪ̯nɐ", "маленький"],
    ["Mensch", "mɛnʃ", "человек"],
    ["stirbt", "ʃtɪʁpt", "умирает"],
    ["nur", "nuːɐ̯", "только"],
    ["zum", "tsʊm", "к"],
    ["Schein", "ʃaɪ̯n", "показуха"],
    ["Wollte", "ˈvɔltə", "Хотел"],
    ["ganz", "ɡant͡s", "полностью"],
    ["alleine", "aˈlaɪ̯nə", "один"],
    ["sein", "zaɪ̯n", "быть"],
    ["Das", "das", "Это"],
    ["stand", "ʃtant", "стояло"],
    ["still", "ʃtɪl", "спокойно"],
    ["für", "fyːɐ̯", "в течение"],
    ["Stunden", "ˈʃtʊndən", "часов"],
    ["So", "zoː", "Так"],
    ["es", "ɛs", "это"],
    ["tot", "toːt", "мертвое"],
    ["befunden", "bəˈfʊndən", "считалось"],
    ["Es", "ɛs", "Это"],
    ["wird", "vɪrt", "становится"],
    ["verscharrt", "fɛɐ̯ˈʃaʁt", "зарыто"],
    ["nassem", "ˈnasəm", "мокром"],
    ["Sand", "zant", "песок"],
    ["Mit", "mɪt", "С"],
    ["einer", "ˈaɪ̯nɐ", "одной"],
    ["Spieluhr", "ˈʃpiːlˌuːɐ̯", "музыкальным ящиком"],
    ["der", "deːɐ̯", "руке"],
    ["Hand", "hant", "рукой"],
    ["kalten", "ˈkaltən", "холодной"],
    ["Winternacht", "ˈvɪntɐˌnaxt", "зимней ночи"],
    ["Ist", "ɪst", "было"],
    ["erwacht", "ɛɐ̯ˈvaxt", "проснулось"],
    ["Als", "als", "Когда"],
    ["Frost", "fʁɔst", "мороз"],
    ["Kind", "kɪnt", "ребенка"],
    ["geflogen", "ɡəˈfloːɡən", "влетел"],
    ["Hat", "hat", "имеет"],
    ["die", "diː", "эту"],
    ["aufgezogen", "ˈaʊ̯fɡəˌt͡soːɡən", "завело"],
    ["Eine", "ˈaɪ̯nə", "Одна"],
    ["Melodie", "meloˈdiː", "мелодия"],
    ["im", "ɪm", "в"],
    ["Wind", "vɪnt", "ветер"],
    ["Und", "ʊnt", "и"],
    ["aus", "aʊ̯s", "из"],
    ["Erde", "ˈɛʁdə", "земли"],
    ["Reiter", "ˈraɪ̯tɐ", "наездник"],
    ["kein", "kaɪ̯n", "нет"],
    ["Engel", "ˈɛŋl̩", "ангел"],
    ["mehr", "meːɐ̯", "больше"],
    ["Regen", "ˈʁeːɡn̩", "дождь"],
    ["weint", "vaɪ̯nt", "плачет"],
    ["am", "am", "на"],
    ["Grab", "ɡʁaːp", "могиле"],
    ["schlägt", "ʃlɛːkt", "бьётся"],
    ["der", "deːɐ̯", "земли"],
    ["singt", "zɪŋt", "поёт"],
    ["kalte", "ˈkaltə", "холодный"],
    ["Mond", "mɔnt", "луна"],
    ["in", "ɪn", "в"],
    ["voller", "ˈfɔlɐ", "полной"],
    ["Pracht", "pʁaxt", "красе"],
    ["Hört", "høːɐ̯t", "слышит"],
    ["die", "diː", "эти"],
    ["Schreie", "ˈʃʁaɪ̯ə", "крики"],
    ["Nacht", "naxt", "ночи"],
    ["steigt", "ʃtaɪ̯kt", "спускается"],
    ["herab", "hɛˈʁaːp", "сюда"],
    ["Nur", "nuːɐ̯", "Только"],
    ["Zwischen", "ˈt͡svɪʃən", "Между"],
    ["harten", "ˈhaʁtən", "твёрдых"],
    ["Eichendielen", "ˈaɪ̯çəndiːlən", "дубовых досок"],
    ["Wird", "vɪrt", "будет"],
    ["mit", "mɪt", "с"],
    ["steigt", "ʃtaɪ̯kt", "спускается"],
    ["herab", "hɛˈʁaːp", "сюда"],
    ["Mein", "maɪ̯n", "Моё"],
    ["nicht", "nɪçt", "не"],
    ["aus", "aʊ̯s", "из"],
    ["Gottes", "ˈɡɔtəs", "Божьего"],
    ["Acker", "ˈakɐ", "поля"],
    ["diese", "ˈdiːzə", "эту"],
    ["Da", "da", "Там"],
    ["ausgebettet", "ˈaʊ̯sɡəˌbɛtət", "извлекли"],
    ["Herz", "hɛʁts", "сердце"],
    ["gerettet", "ɡəˈʁɛtət", "спасли"],
    ["weiter", "ˈvaɪ̯tɐ", "дальше"],
    ["singt", "zɪŋt", "поёт"],
    ["hörten", "ˈhœʁtən", "слышали"],
    ["haben", "ˈhaːbən", "имели"],
  ],
    [ 
    ["wer", "vɛɐ̯", "кто"],
    ["Wer ist lieb? Du oder Tante Em?", "", "Кто милый? Ты или тетя Эмма?"],
    ["Wer bin ich, Onkel?", "", "Кто я, дядя?"],
  ["was", "vas", "что"],
  ["Was ist klein - unsere Wohnung?", "", "Что маленькое? Наша квартира?"],
  ["wann", "van", "когда"],
  ["wo", "voː", "где"],
  ["warum", "vaˈʁʊm", "почему"],
  ["wie", "viː", "как"],
  ["Wie ist mein Vorname, Onkel?", "", "Какое у меня имя, дядя?"],
  ["Wie alt bist du?", "", "Сколько тебе лет?"],
  ["Wie alt bin ich, Onkel?", "", "Сколько мне лет, дядя?"],
  ["welche", "ˈvɛlçə", "какой"],
  ["wohin", "voˈhɪn", "куда"],
  ["woher", "voˈhɛɐ̯", "откуда"],
  ["wie viel", "viː fiːl", "сколько"],
  ["welcher", "ˈvɛlçɐ", "который"], ],

  [   
  ["wer", "vɛɐ̯", "кто"],
  ["was", "vas", "что"],
  ["wann", "van", "когда"],
  ["wo", "voː", "где"],
  ["warum", "vaˈʁʊm", "почему"],
  ["wie", "viː", "как"],
  ["welche", "ˈvɛlçə", "какой"],
  ["wohin", "voˈhɪn", "куда"],
  ["woher", "voˈhɛɐ̯", "откуда"],
  ["wie viel", "viː fiːl", "сколько"],
  ["welcher", "ˈvɛlçɐ", "который"], ],

  [   
  ["Wer bin ich, Onkel?", "", "Кто я, дядя?"],
  ["Wie ist mein Vorname, Onkel?", "", "Какое у меня имя, дядя?"],
  ["Wie alt bist du?", "", "Сколько тебе лет?"],
  ["Wie alt bin ich, Onkel?", "", "Сколько мне лет, дядя?"],
  ["Sind wir Bauern oder Könige?", "", "Мы крестьяне или короли?"],
  ["Wer ist arm - ich, Tante Em oder du?", "ː", "Кто бедный? Я, тетя Эмма или ты?"],
  ["Was ist klein - unsere Wohnung?", "", "Что маленькое? Наша квартира?"],
  ["Wessen Haus ist klein?", "", "Чей дом маленький?"],
  ["Wer ist lieb? Du oder Tante Em?", "", "Кто милый? Ты или тетя Эмма?"],
  ["Also, seid ihr beide lieb?", "", "Значит, вы обе милые?"],
   ],






  [
    


   
      







      ["die Antwort", "diː ˈantvɔʁt", "ответ"],
      ["das Fenster", "das ˈfɛnstɐ", "окно"],
      ["die Frage", "diː ˈfʁaːɡə", "вопрос"],
      ["die Frau", "diː ˈfʁaʊ", "женщина"],
      ["die Geschichte", "diː ɡəˈʃɪçtə", "история"],
      ["das Haus", "das haʊ̯s", "дом"],
      ["das Jahr", "das jaːɐ", "год"],
      ["der Junge", "deːɐ ˈjʊŋə", "мальчик"],
      ["der König", "deːɐ ˈkøːnɪç", "король"],
      ["glauben", "ˈɡlaʊbən", "верить"],
      ["sein", "zaɪ̯n", "быть"],
      ["arm", "aʁm", "бедный"],
      ["auch", "aʊ̯χ", "также"],
      ["besonders", "bəˈzɔndɐs", "особенно"],
      ["genau", "ɡəˈnaʊ̯", "точно"],
      ["groß", "ɡʁoːs", "большой"],
      ["hier", "hiːɐ̯", "здесь"],
      ["hässlich", "ˈhɛslɪç", "уродливый"],
      ["hübsch", "hʏpʃ", "красивый"],
      ["wohnen", "ˈvoːnən", "жить"],
      ["lieb", "liːp", "любимый"],
      ["reich", "ʁaɪ̯ç", "богатый"],
      ["schon", "ʃoːn", "уже"],
      ["schön", "ʃøːn", "красивый"],
      ["sehr", "zeːɐ̯", "очень"],
      ["zusammen", "ˈtsuːzamən", "вместе"],
      ["unser", "ˈʊnzɐ", "наш (мужской род)"],
      ["unsere", "ˈʊnzəʁə", "наша (женский род)"],
      ["euer", "ˈɔʏ̯ɐ", "ваш (мужской род)"],
      ["eure", "ˈɔʏ̯ʁə", "ваша (женский род)"],
      ["seine", "ˈzaɪ̯nə", "его"],
      ["aber", "ˈaːbɐ", "но"],
      ["also", "ˈalzoː", "так что"],
      ["kein", "kaɪ̯n", "нет"],
      ["oder", "ˈoːdɐ", "или"],
      ["keine", "ˈkaɪ̯nə", "нет (ж.р.)"],
      ["beide", "ˈbaɪ̯də", "оба"],
      ["alle", "ˈalə", "все"],
      ["was", "vas", "что"],
      ["wer", "vɛɐ̯", "кто"],
      ["wessen", "ˈvɛsən", "чей"],
      ["wie", "viː", "как"],
      ["zehn", "t͡seːn", "десять"]
    ],
    [



    ["gleich", "ɡlaɪç", "сейчас"],
    ["jetzt", "jɛtst", "сейчас"],
    ["sofort", "zoˈfɔʁt", "немедленно"],
    ["früh", "fʁyː", "рано"],
    ["bald", "balt", "скоро"],
    ["spät", "ʃpɛːt", "поздно"],
    ["heute", "hɔʏ̯tə", "сегодня"],
    ["morgen", "ˈmɔʁɡn̩", "завтра"],
    ["übermorgen", "ˈyːbɐˌmɔʁɡn̩", "послезавтра"],
    ["gestern", "ɡəˈʃtɛʁn", "вчера"],
    ["vorgestern", "ˈfɔʁˌɡɛʃtɛʁn", "позавчера"],
    ["noch", "nɔχ", "ещё"],
    ["schon", "ʃoːn", "уже"],
    ["zuerst", "ˈt͡suːɐ̯st", "сначала"],
    ["vorher", "ˈfoːɐ̯hɐ", "предварительно"],
    ["dann", "dan", "затем"],
    ["danach", "daˈnaχ", "после этого"],
    ["später", "ˈʃpɛːtɐ", "позже"],
    ["früher", "ˈfʁyːɐ", "раньше"],
    ["zuletzt", "ˈt͡suːlɛst", "в конце"],
    ["nachher", "ˈnaːχhɐ", "после этого"],
    ["schließlich", "ˈʃliːsliç", "в конце концов"]
  ],
   [
    ["geradeaus", "ɡəˈʁaːtəˌʔaʊ̯s", "прямо"],
    ["überall", "ˈyːbɐˌal", "везде"],
    ["nirgendwo", "ˈnɪʁɡəntˌvo", "нигде"],
    ["vorwärts", "ˈfoːɐ̯vɛʁts", "вперёд"],
    ["rückwärts", "ˈʁʏkˌvɛʁts", "назад"],
    ["seitlich", "ˈzaɪ̯tlɪç", "сбоку"],
    ["hier", "hiːɐ̯", "здесь"],
    ["dort", "dɔʁt", "там"],
    ["drinnen", "ˈdʁɪnən", "внутри"],
    ["draußen", "ˈdʁaʊ̯sən", "снаружи"],
    ["rechts", "ʁɛçts", "справа"],
    ["links", "lɪŋks", "слева"],
    ["vorne", "ˈfɔʁnə", "впереди"],
    ["hinten", "ˈhɪntn̩", "сзади"],
    ["unten", "ˈʊntn̩", "внизу"],
    ["oben", "ˈoːbn̩", "вверху"],
    ["immer", "ˈɪmɐ", "всегда"],
    ["oft", "ɔft", "часто"],
    ["häufig", "ˈhɔɪ̯fɪç", "часто"],
    ["meistens", "ˈmaɪ̯stəns", "обычно"],
    ["manchmal", "ˈmant͡ʃmaːl", "иногда"],
    ["regelmäßig", "ʁeˈɡɛlˌmɛːsɪç", "регулярно"],
    ["gewöhnlich", "ɡəˈvøːnlɪç", "обычно"],
    ["selten", "ˈzɛltən", "редко"],
    ["wieder", "ˈviːdɐ", "снова"],
    ["viel", "fiːl", "много"],
    ["wenig", "ˈveːnɪç", "мало"],
    ["wenigstens", "ˈveːnɪçstəns", "по крайней мере"],
    ["genug", "ɡəˈnʊk", "достаточно"],
    ["alles", "ˈaləs", "всё"],
    ["fast", "fast", "почти"],
    ["kaum", "kaʊm", "едва"],
    ["so", "zoː", "так"]
  ],
  [
    ["ja", "jaː", "да"],
    ["nein", "naɪ̯n", "нет"],
    ["nicht", "nɪçt", "не"],
    ["gar nicht", "ɡaːɐ̯ nɪçt", "совсем не"],
    ["überhaupt nicht", "ˈyːbɐhaʊ̯pt nɪçt", "совсем не"],
    ["niemals", "ˈniːmals", "никогда"],
    ["nie", "niː", "никогда"],
    ["nirgendwo", "ˈnɪʁɡəntˌvo", "нигде"],
    ["darum", "daˈʁʊm", "поэтому"],
    ["deshalb", "dɛsˈhalp", "поэтому"],
    ["deswegen", "dɛsˈveːɡən", "поэтому"],
    ["dazu", "daˈzuː", "к этому"],
    ["gut", "ɡuːt", "хорошо"],
    ["schlecht", "ʃlɛçt", "плохо"],
    ["schnell", "ʃnɛl", "быстро"],
    ["richtig", "ˈʁɪçtɪç", "правильно"],
    ["gern", "ɡɛʁn", "с удовольствием"]
  ],
  [
    ["leider", "ˈlaɪ̯dɐ", "к сожалению"],
    ["umsonst", "ˈʊmzɔnst", "зря"],
    ["vergeblich", "fɛɐ̯ˈɡɛblɪç", "тщетно"],
    ["hoffentlich", "ˈhɔfntlɪç", "надеюсь"],
    ["sehr", "zeːɐ̯", "очень"],
    ["zu", "tsuː", "слишком"],
    ["ganz", "ɡant͡s", "весьма"],
    ["besonders", "bəˈzɔndɐs", "особенно"],
    ["sogar", "ˈzoːɡaːɐ̯", "даже"],
    ["auch", "aʊ̯χ", "также"],
    ["noch", "nɔχ", "ещё"],
    ["schon", "ʃoːn", "уже"],
    ["nur", "nuːɐ̯", "только"],
    ["vielleicht", "ˈfiːlɪçt", "возможно"],
    ["wahrscheinlich", "ˈvaːʁʃaɪ̯nlɪç", "вероятно"],
    ["vermutlich", "fɛɐ̯ˈmʊtlɪç", "предположительно"],
    ["bestimmt", "bəˈʃtɪmt", "определенно"],
    ["sicher", "ˈzɪçɐ", "уверенно"],
    ["natürlich", "naˈtyːɐlɪç", "конечно"],
    ["wirklich", "ˈvɪʁklɪç", "действительно"]
  ],
  [
    ['laut', '  laʊt  ', 'громко'],
    ['leise', '  laɪ̯zə  ', 'тихо'],
    ['richtig', '  ʁɪçtɪç  ', 'правильно'],
    ['falsch', '  falʃ  ', 'неправильно'],
    ['häufig', '  hɔɪ̯fɪç  ', 'часто'],
    ['selten', '  zɛltən  ', 'редко'],
    ['sofort', '  zoˈfɔɐ̯t  ', 'немедленно'],
    ['gleich', '  ɡlaɪ̯ç  ', 'сразу'],
    ['noch', '  nɔχ  ', 'еще'],
    ['schon', '  ʃɔn  ', 'уже'],
    ['wieder', '  viːdɐ  ', 'снова'],
    ['vielleicht', '  fiːlɪçt  ', 'возможно'],
    ['doch', '  dɔχ  ', 'однако'],
    ['trotzdem', '  tʁɔt͡sdɛm  ', 'все же'],
    ['bald', '  balt  ', 'скоро'],
    ['weit', '  vaɪ̯t  ', 'далеко'],
    ['nah', '  naː  ', 'близко'],
    ['oben', '  oːbən  ', 'вверху'],
    ['unten', '  ʊntən  ', 'внизу'],
  ],

  [
    ['ich', '  ɪç  ', 'я'],
    ['du', '  du  ', 'ты'],
    ['er', '  eːɐ̯  ', 'он'],
    ['sie', '  ziː  ', 'она они'],
    ['es', '  ɛs  ', 'оно'],
    ['wir', '  viːɐ̯  ', 'мы'],
    ['ihr', '  iːɐ̯  ', 'вы её их'],
    ['Sie', '  ziː  ', 'вы (вежливая форма)'],
    ['mein', '  maɪ̯n  ', 'мой'],
    ['dein', '  daɪ̯n  ', 'твой'],
    ['sein', '  zaɪ̯n  ', 'его'],
    ['unser', '  ʊnzɛʁ  ', 'наш'],
    ['euer', '  ɔɪ̯ɐ  ', 'ваш'],
  ],

  [
    ['groß', '  ɡroːs  ', 'большой'],
    ['klein', '  klain  ', 'маленький'],
    ['schnell', '  ʃnɛl  ', 'быстрый'],
    ['langsam', '  laŋˈzam  ', 'медленный'],
    ['schön', '  ʃøːn  ', 'красивый'],
    ['hässlich', '  hɛslɪç  ', 'уродливый'],
    ['stark', '  ʃtaʁk  ', 'сильный'],
    ['klug', '  klʊk  ', 'умный'],
    ['gut', '  ɡuːt  ', 'хороший'],
    ['schlecht', '  ʃlɛçt  ', 'плохой'],
    ['lecker', '  lɛkɐ  ', 'вкусный'],
    ['ekelhaft', '  eːkəlhaft  ', 'отвратительный'],
    ['nett', '  nɛt  ', 'добрый'],
    ['böse', '  bøːzə  ', 'злой'],
    ['fröhlich', '  fʁøːlɪç  ', 'веселый'],
    ['traurig', '  tʁaʊ̯ʁɪç  ', 'грустный'],
    ['ruhig', '  ʁuːɪç  ', 'спокойный'],
    ['laut', '  laʊ̯t  ', 'громкий'],
    ['mutig', '  muːtɪç  ', 'смелый'],
    ['ängstlich', '  ɛŋstlɪç  ', 'боязливый'],
    ['klar', '  klaːɐ̯  ', 'ясный'],
    ['dunkel', '  dʊŋkl̩  ', 'темный'],
    ['sauber', '  zaʊ̯bɐ  ', 'чистый'],
    ['schmutzig', '  ʃmʊtsɪç  ', 'грязный'],
    ['alt', '  alt  ', 'старый'],
    ['frisch', '  fʁɪʃ  ', 'свежий'],
    ['müde', '  myːdə  ', 'уставший'],
    ['intelligent', '  ɪntɛliˈɡɛnt  ', 'умный'],
    ['freundlich', '  fʁɔɪ̯ntlɪç  ', 'дружелюбный'],
    ['feindlich', '  faɪ̯ntlɪç  ', 'враждебный'],
    ['lustig', '  lʊstɪç  ', 'весёлый'],
    ['traurig', '  tʁaʊ̯ʁɪç  ', 'грустный'],
    ['gesund', '  ɡəˈzʊnt  ', 'здоровый'],
    ['krank', '  kʁaŋk  ', 'больной'],
    ['altmodisch', '  altmoːdɪʃ  ', 'устаревший'],
    ['schlau', '  ʃlaʊ̯  ', 'умный'],
    ['dumm', '  dʊm  ', 'глупый'],
    ['interessant', '  ɪntəʁɛsant  ', 'интересный'],
    ['langweilig', '  laŋvaɪ̯lɪç  ', 'скучный'],
    ['mutig', '  muːtɪç  ', 'смелый'],
    ['ängstlich', '  ɛŋstlɪç  ', 'боязливый'],
    ['geduldig', '  ɡəˈdʊldɪç  ', 'терпеливый'],
    ['ungeduldig', '  ʊnɡəˈdʊldɪç  ', 'нетерпеливый'],
    ['fleißig', '  flaɪ̯sɪç  ', 'трудолюбивый'],
    ['faul', '  faʊ̯l  ', 'ленивый'],
    ['schwach', '  ʃvaːx  ', 'слабый'],
    ['dick', '  dɪk  ', 'толстый'],
    ['dünn', '  dʏn  ', 'тонкий'],
    ['jung', '  jʊŋ  ', 'молодой'],
  ],


  [
    ['sein', '  zaɪ̯n  ', 'быть'],
    ['haben', '  haːbən  ', 'иметь'],
    ['gehen', '  ɡeːən  ', 'идти'],
    ['sagen', '  zaːɡən  ', 'сказать'],
    ['machen', '  maxən  ', 'делать'],
    ['wissen', '  vɪsən  ', 'знать'],
    ['kommen', '  kɔmən  ', 'приходить'],
    ['sehen', '  zeːən  ', 'видеть'],
    ['geben', '  ɡeːbən  ', 'давать'],
    ['nehmen', '  neːmən  ', 'брать'],
    ['lesen', '  leːzn̩  ', 'читать'],
    ['sprechen', '  ʃpreːçən  ', 'говорить'],
    ['lernen', '  lɛʁnən  ', 'учиться'],
    ['schreiben', '  ʃʁaɪ̯bən  ', 'писать'],
    ['essen', '  ɛsn̩  ', 'есть'],
    ['trinken', '  trɪŋkən  ', 'пить'],
    ['fahren', '  faːʁən  ', 'ехать'],
    ['schlafen', '  ʃlaːfən  ', 'спать'],
    ['arbeiten', '  aʁbaɪ̯tn̩  ', 'работать'],
    ['spielen', '  ʃpiːlən  ', 'играть'],
    ['bleiben', '  blaɪ̯bn̩  ', 'оставаться'],
    ['fragen', '  fʁaːɡən  ', 'спрашивать'],
    ['hören', '  høːʁən  ', 'слушать'],
    ['wollen', '  vɔlən  ', 'хотеть'],
    ['finden', '  fɪndən  ', 'находить'],
    ['stellen', '  ʃtɛlən  ', 'ставить'],
    ['laufen', '  laʊ̯fn̩  ', 'бегать'],
    ['fahren', '  faːʁən  ', 'водить'],
    ['verstehen', '  fɛɐ̯ˈʃteːən  ', 'понимать'],
    ['kaufen', '  kaʊ̯fn̩  ', 'покупать'],
    ['bekommen', '  bəˈkɔmən  ', 'получать'],
    ['schenken', '  ʃɛŋkən  ', 'дарить'],
    ['zeigen', '  t͡saɪ̯ɡən  ', 'показывать'],
    ['helfen', '  hɛlfən  ', 'помогать'],
    ['mögen', '  møːɡən  ', 'нравиться'],
    ['bauen', '  baʊ̯ən  ', 'строить'],
    ['denken', '  dɛŋkən  ', 'думать'],
    ['spielen', '  ʃpiːlən  ', 'играть'],
    ['schwimmen', '  ʃvɪmən  ', 'плавать'],
    ['tanzen', '  tant͡sn̩  ', 'танцевать'],
    ['fühlen', '  fyːlən  ', 'чувствовать'],
    ['vergessen', '  fɛɐ̯ˈɡɛsn̩  ', 'забывать'],
    ['entscheiden', '  ɛntˈʃaɪ̯dən  ', 'принимать решение'],
    ['beginnen', '  bɪˈɡɪnən  ', 'начинать'],
    ['hassen', '  hasən  ', 'ненавидеть'],
    ['beten', '  beːtn̩  ', 'молиться'],
    ['antworten', '  anˈtvoːʁtən  ', 'отвечать'],
    ['warten', '  vaʁtn̩  ', 'ждать'],
    ['lachen', '  laxən  ', 'смеяться'],
    ['verlassen', '  fɛɐ̯ˈlasn̩  ', 'покидать'],
    ['verlieren', '  fɛɐ̯ˈliːʁən  ', 'терять'],
    ['besuchen', '  bəˈzuːxn̩  ', 'посещать'],
    ['klären', '  klɛːʁən  ', 'разъяснять'],
    ['erklären', '  ɛɐ̯ˈklɛːʁən  ', 'объяснять'],
    ['öffnen', '  œfnən  ', 'открывать'],
    ['schließen', '  ʃliːsn̩  ', 'закрывать'],
    ['verstärken', '  fɛɐ̯ˈʃtɛːɐ̯kn̩  ', 'усиливать'],
    ['leben', '  leːbn̩  ', 'жить'],
    ['verändern', '  fɛɐ̯ˈʔɛndɐn  ', 'изменять'],
    ['gratulieren', '  ɡʁatuˈliːʁən  ', 'поздравлять'],
    ['schaffen', '  ʃafən  ', 'создавать'],
    ['verbinden', '  fɛɐ̯ˈbɪndən  ', 'соединять'],
    ['hören', '  høːʁən  ', 'слышать'],
    ['üben', '  yːbn̩  ', 'практиковаться'],
    ['glauben', '  ɡlaʊ̯bn̩  ', 'верить'],
    ['empfehlen', '  ɛmpˈfeːlən  ', 'рекомендовать'],
    ['verstehen', '  fɛɐ̯ˈʃteːən  ', 'понимать'],
    ['sorgen', '  zɔʁɡən  ', 'заботиться'],
    ['treffen', '  tʁɛfn̩  ', 'встречаться'],
    ['bestellen', '  bəˈʃtɛlən  ', 'заказывать'],
    ['ändern', '  ɛndɐn  ', 'изменять'],
    ['erzählen', '  ɛɐ̯ˈt͡sɛːlən  ', 'рассказывать'],
    ['genießen', '  ɡəˈniːsən  ', 'наслаждаться'],
    ['bewegen', '  bəˈveːɡən  ', 'двигаться'],
    ['vergleichen', '  fɛɐ̯ˈɡlaɪ̯çən  ', 'сравнивать'],
    ['reisen', '  ʁaɪ̯zn̩  ', 'путешествовать'],
    ['stehen', '  ʃteːən  ', 'стоять'],
    ['tun', '  tuːn  ', 'делать'],
    ['werden', '  vɛʁdən  ', 'становиться'],
    ['lernen', '  lɛʁnən  ', 'учиться']
  ],

  [
    ["der Name", " ˈnaːmə ", "имя"],
    ["die Geschichte", " ɡəˈʃɪçtə ", "история"],
    ["der Sport", " ʃpɔʁt ", "спорт"],
    ["die Kunst", " kʊnst ", "искусство"],
    ["der Markt", " maʁkt ", "рынок"],
    ["das Spiel", " ʃpiːl ", "игра"],

    ["die Party", " ˈpaʁti ", "вечеринка"],
    ["der Krieg", " kʁiːk ", "война"],
    ["das Glück", " ɡlʏk ", "счастье"],
    ["die Hoffnung", " ˈhɔfn̩ʊŋ ", "надежда"],
    ["der Erfolg", " ɛɐ̯ˈfɔlɡ ", "успех"],
    ["die Arbeit", " ˈaʁbaɪt ", "работа"],

    ["der Fernseher", " ˈfɛɐ̯nˌzeːɐ̯ ", "телевизор"],

    ["der Stift", " ʃtɪft ", "ручка"],
    ["das Papier", " paˈpiːɐ ", "бумага"],
    ["die Tasche", " ˈtaʃə ", "сумка"],
    ["der Schlüssel", " ˈʃlʏsl̩ ", "ключ"],
    ["die Brille", " ˈbrɪlə ", "очки"],
    ["das Buch", " buːχ ", "книга"],
    ["der Bleistift", " ˈblaɪ̯ʃtɪft ", "карандаш"],
    ["die Schere", " ˈʃeːʁə ", "ножницы"],
    ["der Tisch", " tɪʃ ", "стол"],
    ["der Stuhl", " ʃtuːl ", "стул"],
    ["das Bett", " bɛt ", "кровать"],
    ["die Blume", " ˈbluːmə ", "цветок"],
    ["der Garten", " ˈɡaʁtn̩ ", "сад"],
    ["die Pflanze", " ˈplantsə ", "растение"],
    ["der Himmel", " ˈhɪməl ", "небо"],
    ["die Erde", " ˈeːʁdə ", "земля"],
    ["die Luft", " luft ", "воздух"],
    ["die Sonne", " ˈzɔnə ", "солнце"],
    ["der Mond", " mɔnt ", "луна"],
    ["der Stern", " ʃtɛʁn ", "звезда"],
    ["der Vogel", " ˈfoːɡəl ", "птица"],
    ["das Tier", " tiːɐ ", "животное"],
    ["der Hund", " hʊnt ", "собака"],
    ["die Katze", " ˈkat͡sə ", "кошка"],
    ["das Pferd", " pfeːrt ", "лошадь"],
    ["die Kuh", " kuː ", "корова"],
    ["das Schwein", " ʃvaɪ̯n ", "свинья"],
    ["der Frosch", " fʁɔʃ ", "лягушка"],
    ["der Fisch", " fɪʃ ", "рыба"],
    ["die Maus", " maʊs ", "мышь"],
    ["die Schlange", " ˈʃlaŋə ", "змея"],
    ["der Löwe", " ˈløːvə ", "лев"],
    ["der Tiger", " ˈtiːɡɐ ", "тигр"],
    ["die Giraffe", " ɡiˈʁafə ", "жираф"],
    ["das Elefant", " elɛˈfant ", "слон"],
    ["die Schildkröte", " ˈʃɪltˌkʁøːtə ", "черепаха"],
    ["die Biene", " ˈbiːnə ", "пчела"],
    ["die Spinne", " ˈʃpɪnə ", "паук"],
    ["die Ameise", " aˈmaɪ̯zə ", "муравей"],
    ["die Schnecke", " ˈʃnɛkə ", "улитка"],
    ["der Schmetterling", " ˈʃmɛtəʁlɪŋ ", "бабочка"],
    ["die Libelle", " liˈbɛlə ", "стрекоза"],
    ["die Zeit", " tsaɪt ", "время"],
    ["das Haus", " haʊs ", "дом"],
    ["die Frau", " fʁaʊ ", "женщина"],
    ["die Stadt", " ʃtat ", "город"],
    ["der Tisch", " tɪʃ ", "стол"],
    ["der Apfel", " ˈapfəl ", "яблоко"],
    ["der Hund", " hʊnt ", "собака"],
    ["der Baum", " baʊm ", "дерево"],
    ["die Sonne", " ˈzɔnə ", "солнце"],

    ["das Buch", " buːχ ", "книга"],
    ["die Tür", " tyːr ", "дверь"],
    ["die Hand", " hant ", "рука"],

    ["das Geld", " ɡɛlt ", "деньги"],
    ["der Kunde", " ˈkʊndə ", "клиент"],
    ["die Sprache", " ˈʃpraːxə ", "язык"],
    ["das Telefon", " ˈtɛləˌfoːn ", "телефон"],
    ["der Beruf", " bəˈʁuːf ", "профессия"],
    ["das Jahr", " jaːr ", "год"],
    ["der Flugzeug", " ˈfluːktsɔ͜ʏɡ ", "самолет"],
    ["die Universität", " ˌʊniːvɛʁziˈtɛːt ", "университет"],
    ["das Projekt", " ˈprɔjɛkt ", "проект"],
    ["der Freund", " fʁɔʏnt ", "друг"],
    ["die Familie", " faˈmiːli̯ə ", "семья"],
    ["das Zimmer", " ˈtsɪmɐ ", "комната"],
    ["der Garten", " ˈɡaʁtn̩ ", "сад"],
    ["das Tier", " tiːɐ ", "животное"],
    ["die Natur", " naˈtuːɐ ", "природа"],
    ["der Weg", " veːk ", "дорога"],
    ["die Frage", " ˈfʁaːɡə ", "вопрос"],
    ["das Problem", " ˈpʁoːblɛm ", "проблема"],
    ["der Chef", " ʃɛf ", "шеф"],
    ["die Zeitung", " ˈtsaɪtʊŋ ", "газета"],
    ["die Liebe", " ˈliːbə ", "любовь"],
    ["das Dorf", " dɔʁf ", "деревня"],
    ["der Zug", " tsuːk ", "поезд"],
    ["die Schule", " ˈʃuːlə ", "школа"],
    ["der Plan", " plaːn ", "план"],
    ["das Essen", " ˈɛsən ", "еда"],
    ["die Gesundheit", " ɡəˈzʊntˌhaɪt ", "здоровье"],
  ],

  [
    ["der Apfel", "  apfl̩  ", "яблоко"],
    ["die Banane", "  baˈnaːnə  ", "банан"],
    ["die Birne", "  bɪrnə  ", "груша"],


    ["die Zitrone", "  tsɪtʁoːnə  ", "лимон"],
    ["die Limette", "  lɪˈmɛtə  ", "лайм"],

    ["die Melone", "  meˈloːnə  ", "дыня"],
    ["die Wassermelone", "  vasɐmeˌloːnə  ", "арбуз"],

    ["die Pfirsich", "  pfɪʁziç  ", "персик"],
    ["die Erdnuss", "  eːɐ̯tˌnʊs  ", "арахис"],
 

    ["der Kaffee", "  kafeː  ", "кофе"],
    ["der Tee", "  teː  ", "чай"],
    ["die Milch", "  mɪlç  ", "молоко"],
    ["der Zucker", "  tsuːkɐ  ", "сахар"],
    ["das Wasser", "  vasɐ  ", "вода"],

    ["der Wein", "  vaɪn  ", "вино"],

    ["das Brötchen", "  bʁœtçən  ", "булочка"],
    ["das Croissant", "  kʁwaˈsɑ̃  ", "круассан"],
    ["das Gebäck", "  ɡəˈbɛk  ", "выпечка"],
    ["der Kuchen", "  kuːxn̩  ", "торт"],
    ["die Torte", "  tɔʁtə  ", "торт"],
    ["die Schokolade", "  ʃokolaˈdə  ", "шоколад"],
    ["das Eis", "  aɪs  ", "мороженое"],
    ["das Sandwich", "  sændvɪʃ  ", "бутерброд"],
    ["das Frühstück", "  fʁyːʃtʏk  ", "завтрак"],
    ["das Mittagessen", "  mɪtaɡˌɛsn̩  ", "обед"],
    ["das Abendessen", "  aːbntˌɛsn̩  ", "ужин"],
    ["die Suppe", "  zʊpə  ", "суп"],
    ["der Salat", "  zaˈlaːt  ", "салат"],
    ["das Gemüse", "  ɡəˈmyːzə  ", "овощи"],
    ["das Fleisch", "  flaɪʃ  ", "мясо"],
    ["der Fisch", "  fɪʃ  ", "рыба"],
    ["die Wurst", "  vʊʁst  ", "колбаса"],
    ["das Ei", "  aɪ  ", "яйцо"],
    ["das Omelett", "  ɔməˈlɛt  ", "омлет"],
    ["der Kellner", "  kɛlnɐ  ", "официант"],
    ["die Bedienung", "  beˈdiːnʊŋ  ", "обслуживание"],
    ["die Rechnung", "  ʁɛçnʊŋ  ", "счет"],
    ["die Reservierung", "  ʁezeʁvɪˈʁʊŋ  ", "бронирование"],
    ["das Trinkgeld", "  tʁɪŋkɡɛlt  ", "чаевые"],
    ["der Tisch", "  tɪʃ  ", "стол"]],

  [
    ["die Karotte", "  kaˈrɔtə  ", "морковь"],
    ["die Tomate", "  toˈmaːtə  ", "помидор"],
    ["die Kartoffel", "  karˈtɔfəl  ", "картофель"],
    ["die Zwiebel", "  t͡sviːbl̩  ", "лук"],


    ["der Kürbis", "  kʏʁbɪs  ", "тыква"],
    ["der Rettich", "  rɛtɪç  ", "редька"],
    ["die Gurke", "  ɡʊrkə  ", "огурец"],
    ["die Paprika", "  paˈpʁiːka  ", "перец"],

    ["die Bohne", "  boːnə  ", "фасоль"],
    ["die Erbse", "  ɛʁpsə  ", "горох"],
    ["die Möhre", "  møːrə  ", "морковь"],

    ["der Knoblauch", "  knɔblaʊx  ", "чеснок"],
 
    ['Kopf', '/kɔpf/', 'Голова'],
    ['Hals', '/haːls/', 'Шея'],
    ['Schulter', '/ˈʃʊltɐ/', 'Плечо'],
    ['Arm', '/arm/', 'Рука'],
    ['Brust', '/brʊst/', 'Грудь'],
    ['Bauch', '/baʊχ/', 'Живот'],
    ['Lenden', '/ˈlɛndən/', 'Поясница'],
    ['Becken', '/ˈbɛkən/', 'Таз'],
    ['Bein', '/baɪn/', 'Нога'],
    ['Fuß', '/fuːs/', 'Стопа'],
    ['Hand', '/hant/', 'Рука'],
    ['Rücken', '/ˈrʏkən/', 'Спина'],
    ['Ellenbogen', '/ˈɛlənboːɡən/', 'Локоть'],
    ['Knie', '/kniː/', 'Колено'],
    ['Schulterblatt', '/ˈʃʊltɐblat/', 'Лопатка'],
    ['Zeh', '/tseː/', 'Палец на ноге'],
    ['Nacken', '/ˈnakən/', 'Затылок'],
    ['Handgelenk', '/ˈhantˌɡeːlɛŋk/', 'Запястье'],
    ['Oberschenkel', '/ˈoːbɐʃɛŋkl̩/', 'Бедро'],
    ['Zunge', '/ˈtsʊŋə/', 'Язык']

  ],
  [
    ['Messer', '/ˈmɛsɐ/', 'нож'],
    ['Gabel', '/ˈɡaːbəl/', 'вилка'],
    ['Löffel', '/ˈlœfl̩/', 'ложка'],
    ['Teller', '/ˈtɛlɐ/', 'тарелка'],
    ['Glas', '/ɡlɑːs/', 'стакан'],
    ['Tasse', '/ˈtasə/', 'чашка'],
    ['Pfanne', '/ˈpfanə/', 'сковорода'],
    ['Topf', '/tɔpf/', 'кастрюля'],
    ['Schere', '/ˈʃeːʁə/', 'ножницы'],
    ['Brett', '/bʁɛt/', 'доска'],
    ['Kessel', '/ˈkɛsl̩/', 'чайник'],
    ['Mixer', '/ˈmɪksɐ/', 'блендер'],
    ['Mikrowelle', '/ˈmɪkʁoˌvɛlə/', 'микроволновка'],
    ['Kühlschrank', '/ˈkʏlˌʃʁaŋk/', 'холодильник'],
    ['Backofen', '/ˈbakˌoːfn̩/', 'духовка'],
    ['Herd', '/hɛʁt/', 'плита'],
    ['Serviette', '/sɛɐ̯ˈviːtə/', 'салфетка'],
    ['Reibe', '/ˈʁaɪbə/', 'тёрка'],
    ['Krug', '/kʁuːɡ/', 'кувшин'],
    ['Tablett', '/taˈblɛt/', 'поднос']

 
    ['Zahnbürste', '/ˈtsaːnbyːʁstə/', 'Зубная щетка'],
    ['Zahnpasta', '/ˈtsaːnˌpasta/', 'Зубная паста'],
    ['Seife', '/ˈzaɪ̯fə/', 'Мыло'],
    ['Shampoo', '/ʃamˈpuː/', 'Шампунь'],
    ['Conditioner', '/kɔndiˈtsiːnɐ/', 'Кондиционер'],
    ['Kamm', '/kam/', 'Расческа'],
    ['Föhn', '/føːn/', 'Фен'],
    ['Spiegel', '/ˈʃpiːɡl̩/', 'Зеркало'],
    ['Handtuch', '/ˈhantʊx/', 'Полотенце'],
    ['Badewanne', '/ˈbaːdəˌvanə/', 'Ванна'],
    ['Dusche', '/ˈdʊʃə/', 'Душ'],
    ['Waschmaschine', '/ˈvaʃˌmaʃiːnə/', 'Стиральная машина'],
    ['Waschbecken', '/ˈvaʃˌbɛkən/', 'Умывальник'],
    ['Toilette', '/toːˈlɛtə/', 'Туалет'],
    ['Duschvorhang', '/ˈdʊʃˌfoːrhaŋ/', 'Шторка для душа'],
    ['Rasierschaum', '/raˈziːɐˌʃaʊ̯m/', 'Пена для бритья'],
    ['Zahnseide', '/ˈtsaːnˌzaɪ̯də/', 'Зубная нить'],
    ['Toilettenbürste', '/toːˈlɛtənˌbyːʁstə/', 'Щетка для унитаза'],
    ['Duschgel', '/ˈdʊʃˌɡɛl/', 'Гель для душа'],
    ['Regal', '/ˈʁeːɡaːl/', 'Полка']


  ],

  [["das Bett", "[bɛt]", "кровать"],
  ["das Kissen", "[ˈkɪsn̩]", "подушка"],
  ["die Bettdecke", "[ˈbɛtˌdɛkə]", "одеяло"],
  ["das Laken", "[ˈlaːkən]", "простыня"],
  ["der Nachttisch", "[ˈnaxtˌtɪʃ]", "тумбочка"],
  ["der Schrank", "[ʃʁaŋk]", "шкаф"],
  ["der Kleiderschrank", "[ˈklaɪ̯dɐˌʃʁaŋk]", "шкаф для одежды"],
  ["die Kommode", "[kɔˈmɔdə]", "комод"],
  ["der Teppich", "[ˈtɛpɪç]", "ковер"],
  ["das Fenster", "[ˈfɛnstɐ]", "окно"],
  ["der Vorhang", "[ˈfoːɐ̯haŋ]", "шторы"],
  ["der Spiegel", "[ˈʃpiːɡl̩]", "зеркало"],
  ["das Kopfkissen", "[das ˈkɔpfˌkɪsn̩]", "наволочка"],
  ["die Zudecke", "[diː ˈtsuːdɛkə]", "одеяло"],
  ["die Matratze", "[diː maˈtʁaːtsə]", "матрас"],
  ["das Bettlaken", "[das ˈbɛtˌlaːkən]", "простыня на кровати"],
  ["der Wecker", "[dɛɐ̯ ˈvɛkɐ]", "будильник"],
  ["der Radiowecker", "[dɛɐ̯ ˈʁaːdioˌvɛkɐ]", "радиобудильник"],
  ["der Kleiderbügel", "[dɛɐ̯ ˈklaɪ̯dɐˌbyːɡl̩]", "вешалка для одежды"],
  ["die Schublade", "[diː ˈʃuːbˌlaːdə]", "выдвижной ящик"],
  ["der Teppichboden", "[dɛɐ̯ ˈtɛpɪçˌboːdn̩]", "ковровое покрытие"],
  ["die Nachtlampe", "[diː ˈnaxtˌlampə]", "ночник"],
  ["die Stehlampe", "[diː ˈʃteːlˌlampə]", "стоячая лампа"],
  ["der Deckenventilator", "[dɛɐ̯ ˈdɛkənˌfɛntilatoːɐ̯]", "потолочный вентилятор"],
  ["der Schreibtisch", "[dɛɐ̯ ˈʃʁaɪ̯bˌtɪʃ]", "письменный стол"],
  ["der Sessel", "[dɛɐ̯ ˈzɛsl̩]", "кресло"],
  ["der Spiegelrahmen", "[dɛɐ̯ ˈʃpiːɡl̩ˌʁaːmn̩]", "рама для зеркала"]
  
    ["der Schreibtisch", "[dɛɐ̯ ˈʃʁaɪ̯bˌtɪʃ]", "письменный стол"],
    ["der Bürostuhl", "[dɛɐ̯ ˈbyːʁoˌʃtuːl]", "офисное кресло"],
    ["der Aktenschrank", "[dɛɐ̯ ˈaktn̩ˌʃʁaŋk]", "шкаф для документов"],
    ["der Computer", "[dɛɐ̯ kɔmˈpjuːtɐ]", "компьютер"],
    ["der Bildschirm", "[dɛɐ̯ ˈbɪltˌʃɪʁm]", "монитор"],
    ["die Maus", "[diː maʊ̯s]", "мышь"],
    ["die Tastatur", "[diː ˈtastaˌtuːɐ̯]", "клавиатура"],
    ["der Drucker", "[dɛɐ̯ ˈdʁʏkɐ]", "принтер"],
    ["der Tintenstrahldrucker", "[dɛɐ̯ ˈtɪntənʃtʁaːlˌdʁʏkɐ]", "струйный принтер"],
    ["der Laserdrucker", "[dɛɐ̯ ˈleɪzɐˌdʁʏkɐ]", "лазерный принтер"],
    ["der Aktenordner", "[dɛɐ̯ ˈaktn̩ˌʔɔɐ̯dnɐ]", "папка для документов"],
    ["der Kugelschreiber", "[dɛɐ̯ ˈkuːɡl̩ˌʃʁaɪ̯bɐ]", "шариковая ручка"],
    ["das Notizbuch", "[das noˈtiːsˌbʊç]", "записная книжка"],
    ["der Kalender", "[dɛɐ̯ ˈkalɛndɐ]", "календарь"],
    ["die Büroklammer", "[diː ˈbyːʁoˌklamɐ]", "скрепка"]
  ],
  

]

export default w1