// words.js
export const words = [
      ["Ich gucke oft fern.", "[ɪç ˈɡʊkə ʊft fɛʁn]", "Я часто смотрю телевизор.", ""],
      ["Hältst du das?", "[hɛlst du das?]", "Ты это держишь?", ""],
      ["Lass mich in Ruhe!", "[las mɪç ɪn ˈʁuːə!]", "Оставь меня в покое!", ""],
      ["Hast du das bemerkt?", "[hast du das bəˈmɛʁkt?]", "Ты это заметил?", ""],
      ["Wir reden über alles.", "[viːʁ ˈʁeːdn̩ ˈyːbɐ ˈaləs]", "Мы разговариваем обо всем.", ""],
      ["Kannst du das sehen?", "[kʰanst du das ˈzeːən?]", "Ты это видишь?", ""],
      ["Er will hingucken, aber er zögert.", "[ɛʁ vɪl ˈhɪŋˌʔʊkən, ˈabɐ ɛʁ ˈt͡søːɡɐt]", "Он хочет посмотреть, но он колеблется.", ""],
      ["Erinnerst du dich an unseren letzten Urlaub?", "[ɛˈʁɪnɐst du dɪç an ˈʊnzeʁən ˈlɛtstən ˈʊʁlaʊ̯p?]", "Ты помнишь наш последний отпуск?", ""],
      ["Ich gebe dir das Buch.", "[ɪç ˈɡeːbə diːɐ das bʊx]", "Я даю тебе книгу.", ""],
      ["Er hat seinen Schlüssel verloren.", "[ɛʁ hat ˈzaɪ̯nən ˈʃlʏsəl fɛʁˈlɪʁən]", "Он потерял свой ключ.", ""],
      ["Ich versuche es zu verstehen.", "[ɪç fɛʁˈzuːxə ɛs tsuː fɛʁˈʃteːən]", "Я пытаюсь понять это.", ""],
      ["Ich vertraue dir.", "[ɪç fɛʁˈtʁaʊ̯ə diːɐ]", "Я тебе доверяю.", ""],
      ["Erzähl mir mehr!", "[ɛʁˈt͡seːl mɪʁ meːɐ]", "Расскажи мне больше!", ""],
      ["Ich denke, das ist richtig.", "[ɪç ˈdɛŋkə das ɪst ˈʁɪçtɪç]", "Я думаю, что это правильно.", ""],
      ["Hast du vergessen, was du gesagt hast?", "[hast du fɛʁˈɡɛsən vas du ɡəˈzaːkt hast?]", "Ты забыл, что сказал?", ""],
      ["Weißt du, wie spät es ist?", "[vaɪ̯st du viː ʃpɛːt ɛs ɪst?]", "Ты знаешь, который час?", ""],
      ["Ich schlafe gerne.", "[ɪç ˈʃlaːfə ˈɡɛʁnə]", "Я люблю спать.", ""],
      ["Ich wache jeden Morgen um 7 Uhr auf.", "[ɪç ˈvaχə ˈjeːdn̩ ˈmɔʁɡn̩ ʊm ˈziːbn̩ ʊːɐ aʊ̯f]", "Я просыпаюсь каждое утро в 7 часов.", ""],
      ["Er hört nie auf zu arbeiten.", "[ɛʁ hœʁt niː aʊ̯f tsuː ˈaʁbaɪ̯tn̩]", "Он никогда не прекращает работать.", ""],
      ["Er lügt ständig.", "[ɛʁ lʏːɡt ˈʃtɛndɪç]", "Он постоянно лжет.", ""],
      ["Guck mal!", "[ɡʊk mal]", "Посмотри!", ""],
      ["Wir gucken uns einen Film an.", "[viːɐ̯ ˈɡʊkən ʊns ˈaɪ̯nən fɪlm an]", "Мы смотрим фильм.", ""],
      ["Warum guckst du so?", "[ˈvaːʁʊm ˈɡʊkst du zoː]", "Почему ты так смотришь?", ""],
      ["Er guckt durch das Fenster.", "[ɛʁ ˈɡʊkt dʊʁç das ˈfɛnstɐ]", "Он смотрит через окно.", ""],
      ["Ich habe es bemerkt.", "[bəˈmɛʁkən]", "замечать", ""],
      ["Hast du das gesehen?", "[ˈɡʊkən]", "смотреть", ""],
      ["Er hielt das Glas fest.", "[ˈhaltən]", "держать", ""],
      ["Er lässt mich in Ruhe.", "[ˈlasən]", "оставлять, позволять", ""],
      ["Wir haben über alles geredet.", "[ˈʁeːdn̩]", "разговаривать", ""],
      ["Hast du ihn gesehen?", "[ɡəˈzeːən]", "видеть", ""],
      ["Schau mal da hin!", "[ˈhɪŋˌʔʊkən]", "смотреть", ""],
      ["Er erinnerte mich daran.", "[ɛˈʁɪnəʁn]", "напоминать", ""],
      ["Er gab mir das Buch.", "[ˈɡeːbn̩]", "давать", ""],
      ["Ich habe meinen Schlüssel verloren.", "[fɛʁˈlɪʁən]", "терять", ""],
      ["Er versuchte es noch einmal.", "[fɛʁˈzuːxən]", "пытаться", ""],
      ["Ich vertraue ihm.", "[fɛʁˈtʁaʊ̯ən]", "доверять", ""],
      ["Sie erzählte mir eine Geschichte.", "[ɛʁˈt͡seːlən]", "рассказывать", ""],
      ["Ich dachte, es wäre besser.", "[ˈdɛŋkən]", "думать", ""],
      ["Ich habe das vergessen.", "[fɛʁˈɡɛsən]", "забывать", ""],
      ["Weißt du das?", "[ˈvɪsən]", "знать", ""],
      ["Er hat tief geschlafen.", "[ˈʃlaːfn̩]", "спать", ""],
      ["Ich wachte früh auf.", "[ˈaʊ̯fˌvaχən]", "просыпаться", ""],
      ["Sie hörte auf zu arbeiten.", "[ˈaʊ̯fˌhøːʁən]", "прекращать", ""],
      ["Er hat gelogen.", "[ˈlyːɡən]", "лгать", ""],
      ["Hast du das gesehen?", "[ˈɡʊkən]", "смотреть", ""],
      ["Das war nur bedingt richtig.", "[bəˈdɪŋt]", "условно", ""],
      ["Das war ein ständiges Problem.", "[ˈʃtɛndlɪç]", "постоянный", ""],
      
      ["denn", "[dɛn]", "потому что", ""],
      ["etwas", "[ˈɛtvɑs]", "что-то", ""],
      ["ganze", "[ˈɡant͡sə]", "целый", ""],
      ["Zeit", "[tsaɪ̯t]", "время", ""],
      ["vorbei", "[fɔʁˈbaɪ̯]", "мимо", ""],
      ["glaube", "[ˈɡlaʊbə]", "верю", ""],
      ["einfach", "[ˈaɪ̯nfaχ]", "простой", ""],
      ["nur", "[nuːɐ]", "только", ""],
      ["weggeguckt", "[ˈvɛkɡəˌkʊkt]", "отведенный взгляд", ""],
      ["entscheidenden", "[ɛntˈʃaɪ̯dən̩dən]", "решающий", ""],
      ["Unterschied", "[ˈʊntɐʃiːt]", "различие", ""],
      ["zwischen", "[ˈt͡svɪʃən]", "между", ""],
      ["hingucken", "[ˈhɪŋˌʔʊkən]", "смотреть", ""],
      ["Ich neige dazu", "[ɪç ˈnaɪ̯ɡə daˈtsuː]", "Я склонен", ""],
      ["neige", "[ˈnaɪ̯ɡə]", "склоняться", ""],
      ["dazu", "[daˈtsuː]", "к этому", ""],
      ["solche", "[ˈzɔlçə]", "такие", ""],
      ["Dinge", "[ˈdɪŋə]", "вещи", ""],
      ["bemerken", "[bəˈmɛʁkən]", "замечать", ""],
      ["sicher", "[ˈzɪçɐ]", "уверенный", ""],
      ["ich sicher", "[ɪç ˈzɪçɐ]", "я уверен", ""],
      ["glaube", "[ˈɡlaʊbə]", "верю", ""],
      ["Sie", "[ziː]", "вы", ""],
      ["gewisser", "[ɡəˈvɪsɐ]", "определенный", ""],
      ["Weise", "[ˈvaɪ̯zə]", "способ", ""],
      ["erinnere", "[ɛˈʁɪnəʁə]", "напоминаю", ""],
      ["unbedingt", "[ˈʊnbədɪŋt]", "обязательно", ""],
      ["Reden", "[ˈʁeːdn̩]", "разговаривать", ""],
      ["gesehen", "[ɡəˈzeːən]", "видел", ""],
      ["Niemand", "[ˈniːmand]", "никто", ""],
      ["ihn", "[iːn]", "его", ""],
      ["eingeschlossen", "[ˈaɪ̯nɡəˌʃlɔsən]", "заперся", ""],
      ["träumt", "[tʁɔʏmt]", "мечтает", ""],
      ["Geben", "[ˈɡeːbn̩]", "давать", ""],
      ["Schuld", "[ʃʊlt]", "вина", ""],
      ["über", "[ˈyːbɐ]", "о", ""],
      ["nach", "[naχ]", "после", ""],
      ["über ihn nach", "[ˈyːbɐ iːn naχ]", "размышлять о нем", ""],
      ["versucht", "[fɛɐˈzuːxt]", "пытался", ""],
      ["aufzunehmen", "[ˈaʊfˌtsuːˌneːmən]", "взять на заметку", ""],

        ["Erzählen", "[ɛʁˈt͡seːlən]", "рассказывать", "https://www.rbc.ua/static/img/_/2/_2_freepik_com_6_1200x675.jpg"],
        ["Vormittag", "[ˈfɔʁˌmɪtaːk]", "утро", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTs_TUtVVieDq5FD04vNpZIGPOuwVIz0Fct_FHJhmdFl1xxZeqxyzHjhBPplxldBj0PhBY&usqp=CAU"],
        ["Anfang", "[ˈanfʊŋ]", "начало", "https://previews.123rf.com/images/creativepriyanka/creativepriyanka2202/creativepriyanka220201520/183526792-symbol-f%C3%BCr-anfang-start.jpg"],
        ["aufwachen", "[ˈaʊ̯fˌvaχən]", "просыпаться", "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55"],
        ["schlafen", "[ˈʃlaːfn̩]", "спать", "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55"],
        ["gar nicht", "[ɡaːɐ̯ nɪçt]", "совсем не", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCBlwZsrjf3o9BJKMPtU71kSVh1hkH82FlGUr_pCXxXRILC48RggsqskyJceUivpZ6AEY&usqp=CAU"],
        ["aufhören", "[ˈaʊ̯fˌhøːʁən]", "прекращать", "https://im.contentlounge.net/styles/manual_crop/s3/2021-01/imago_102115889_n_38728.jpg?im=AspectCrop%2Csize%3D%2816%2C9%29%2Cgravity%3DCenter%2CallowExpansion%2CBackgroundColor%2Ccolor%3Dtransparent&hash=b681da7f538643416402769ee89a4249d5da3c828b87a79df4a24cecf7f65ecd"],
        ["liegen", "[ˈliːɡn̩]", "лежать", "https://news.store.rambler.ru/img/2c84a7faa0e109a9ab685e1656e4308f?img-format=auto&img-1-resize=height:400,fit:max&img-2-filter=sharpen"],
        ["allein", "[aˈlaɪ̯n]", "один", "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5"],
        ["Bett", "[bɛt]", "кровать", "https://images.unsplash.com/photo-1517705008128-361805f42e86"],
        ["meinen", "[ˈmaɪ̯nən]", "иметь в виду", "https://images.unsplash.com/photo-1517842645767-c639042777db"],
        ["Tochter", "[ˈtɔχtɐ]", "дочь", "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e"],
        ["Freunde", "[ˈfʁɔʏndə]", "друзья", "https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a"],
        ["aushalten", "[ˈaʊ̯shaltən]", "выдерживать", "https://images.unsplash.com/photo-1517705008128-361805f42e86"],
        ["letzte", "[ˈlɛt͡stʏ]", "последний", "https://images.unsplash.com/photo-1501139083538-013e3aa90ee1"],
        ["Nacht", "[naχt]", "ночь", "https://images.unsplash.com/photo-1498496294664-d9372eb521f3"],
        ["verständlich", "[fɛʁˈʃtɛntlɪç]", "понятно", "https://images.unsplash.com/photo-1517842645767-c639042777db"],
        ["müssen", "[ˈmʏsən]", "должен", "https://images.unsplash.com/photo-1517705008128-361805f42e86"],
        ["inakzeptabel", "[ɪnaksɛpˈtaːbl̩]", "неприемлемый", "https://images.unsplash.com/photo-1518199266791-5375a83190b7"],
        ["aussprechen", "[ˈaʊ̯sˌpʁɛçən]", "говорить вслух", "https://images.unsplash.com/photo-1517842645767-c639042777db"],
        ["in Ordnung", "[ɪn ˈɔʁdnʊŋ]", "в порядке", "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5"],
        ["im Stich lassen", "[ɪm ˈʃtɪç ˈlasən]", "оставить в беде", "https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a"],
        ["verlieren", "[fɛʁˈlɪʁən]", "терять", "https://images.unsplash.com/photo-1518199266791-5375a83190b7"],
        ["Ansprüche", "[ˈanˌʃpʁʏxə]", "требования", "https://images.unsplash.com/photo-1517705008128-361805f42e86"],
        ["versuchen", "[fɛʁˈzuːxən]", "пытаться", "https://images.unsplash.com/photo-1517842645767-c639042777db"],
        ["vertrauen", "[fɛʁˈtʁaʊ̯ən]", "доверять", "https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a"],
        ["Therapie", "[tɛʁaˈpiː]", "терапия", "https://images.unsplash.com/photo-1576091160550-2173dba999ef"],
        ["neue", "[ˈnɔʏə]", "новый", "https://images.unsplash.com/photo-1501139083538-013e3aa90ee1"],
        ["Therapeut", "[tɛʁaˈpɔʏt]", "терапевт", "https://images.unsplash.com/photo-1576091160550-2173dba999ef"],
        ["erzählen", "[ɛʁˈt͡seːlən]", "рассказывать", "https://images.unsplash.com/photo-1517842645767-c639042777db"],
        ["warum", "[vaˈʁʊm]", "почему", "https://images.unsplash.com/photo-1517842645767-c639042777db"],
        ["nicht können", "[nɪçt ˈkœnən]", "не мочь", "https://images.unsplash.com/photo-1518199266791-5375a83190b7"],
        ["geht", "[ɡeːt]", "можно", "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5"],
        ["denken", "[ˈdɛŋkən]", "думать", "https://images.unsplash.com/photo-1517842645767-c639042777db"],
        ["wichtig", "[ˈvɪçtɪç]", "важно", "https://images.unsplash.com/photo-1517705008128-361805f42e86"],
        ["vergessen", "[fɛʁˈɡɛsən]", "забывать", "https://images.unsplash.com/photo-1518199266791-5375a83190b7"],
        ["real", "[ʁeˈaːl]", "реально", "https://images.unsplash.com/photo-1499951360447-b19be8fe80f5"],
        ["sehen", "[ˈzeːən]", "видеть", "https://images.unsplash.com/photo-1541781774459-bb2af2f05b55"],
        ["dort", "[dɔʁt]", "там", "https://images.unsplash.com/photo-1501139083538-013e3aa90ee1"],
        ["wissen", "[ˈvɪsən]", "знать", "https://images.unsplash.com/photo-1517842645767-c639042777db"],
        ["versuchen", "[fɛʁˈzuːxən]", "пытаться", "https://images.unsplash.com/photo-1517842645767-c639042777db"],
        ["liebe", "[ˈliːbə]", "любовь", "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e"],
        ["später", "[ˈʃpɛːtɐ]", "позже", "https://images.unsplash.com/photo-1501139083538-013e3aa90ee1"],
        ["geben", "[ˈɡeːbn̩]", "давать", "https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a"],
        ["nicht erzählen", "[nɪçt ɛʁˈt͡seːlən]", "не рассказывать", "https://images.unsplash.com/photo-1518199266791-5375a83190b7"]
   
   
    
  ];
  