
const shuffleArray = (array) => {
    for (let i = array.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [array[i], array[j]] = [array[j], array[i]];
    }
  };
  

let questions = { 
    
    help:[
[['ich'],['bin']],
[['du'],['bist']],
[['er,sie,es'],['ist']],
[['wir'],['sind']],
[['ihr'],['seid']],
[['Sie,sie'],['sind']],
// [["Wer"], ["Кто"]],
// [["Was"], ["Что"]],
// [["Wann"], ["Когда"]],
// [["Wo"], ["Где"]],
// [["Woher"], ["Откуда"]],
// [["Wohin"], ["Куда"]],
// [["Wie"], ["Как"]],
// [["Warum"], ["Почему"]],
// [["Wieso"], ["Почему"]],
// [["Weshalb"], ["Почему"]],
// [["Welcher"], ["Какой"]],
// [["Wozu"], ["Зачем"]],
// [["Wem"], ["Кому"]],
    ],

    questions:[
    {
    questionRus: "Где ты",
    questionGerm: "Wo _ du?",
    v1: "bin",
    v2: "ist",
    v3: "bist",
    v4: "sind",
    answer: "bist",
},

{
    questionRus: "где они",
    questionGerm: "Wo _ sie?",
    v1: "sind",
    v2: "seid",
    v3: "bist",
    v4: "sind",
    answer: "sind",
},

{
    questionRus: "где она",
    questionGerm: "Wo _ sie?",
    v1: "sind",
    v2: "ist",
    v3: "bist",
    v4: "sind",
    answer: "ist",
},

{
    questionRus: "где они",
    questionGerm: "Wo _ sie?",
    v1: "seid",
    v2: "ist",
    v3: "bist",
    v4: "sind",
    answer: "ist",
},

{
    questionRus: "где он",
    questionGerm: "Wo _ er?",
    v1: "seid",
    v2: "ist",
    v3: "bist",
    v4: "sind",
    answer: "ist",
},


{
    questionRus: "Откуда ты?",
    questionGerm: "Woher _ du??",
    v1: "kam",
    v2: "kommen",
    v3: "kommst",
    v4: "kommt",
    answer: "kommst",
},

{
    questionRus: "откуда она пришла",
    questionGerm: "Woher _ sie?",
    v1: "kam",
    v2: "kommen",
    v3: "kommst",
    v4: "kommt",
    answer: "kam",
},


{
    questionRus: "Вы упали с велосипеда",
    questionGerm: "Sie _ vom Fahrrad gefallen?",
    v1: "seid",
    v2: "ist",
    v3: "bist",
    v4: "sind",
    answer: "sind",
},

{
    questionRus: "Ты приехал на велосипеде.",
    questionGerm: "Du _ mit dem Fahrrad gefahren.",
    v1: "seid",
    v2: "ist",
    v3: "bist",
    v4: "sind",
    answer: "bist",
},

{
    questionRus: "Мы шли в класс.",
    questionGerm: "Wir _ zum Unterricht zu Fuß gegangen",
    v1: "seid",
    v2: "ist",
    v3: "bist",
    v4: "sind",
    answer: "sind",
},

{
    questionRus: "Вы сегодня встали в 7 часов.",
    questionGerm: "Ihr _ heute um 7 Uhr aufgestanden.",
    v1: "seid",
    v2: "ist",
    v3: "bist",
    v4: "sind",
    answer: "seid",
},

{
    questionRus: "Они родились в Киеве.",
    questionGerm: "Sie _ in Kiev geboren.",
    v1: "seid",
    v2: "ist",
    v3: "bist",
    v4: "sind",
    answer: "sind",
},



{
    questionRus: "Ты уже долго здесь?",
    questionGerm: "_ du schon lange hier?",
    v1: "seid",
    v2: "ist",
    v3: "bist",
    v4: "sind",
    answer: "bist",
},

{
    questionRus: "Когда вы родились?",
    questionGerm: "_ bist du geboren?",
    v1: "Wann",
    v2: "Wo",
    v3: "wer",
    v4: "Wie",
    answer: "Wann",
},

{
    questionRus: "Как ты поживаешь?",
    questionGerm: "_ geht es dir?",
    v1: "Wer",
    v2: "Wo",
    v3: "Wie",
    v4: "Wann",
    answer: "Wie",
  },
  {
    questionRus: "Где ты живешь?",
    questionGerm: "_ wohnst du?",
    v1: "Wann",
    v2: "Wo",
    v3: "Wie",
    v4: "Wer",
    answer: "Wo",
  },
  {
    questionRus: "Как тебя зовут?",
    questionGerm: "_ heißt du?",
    v1: "Wie",
    v2: "Wo",
    v3: "Wann",
    v4: "Wer",
    answer: "Wie",
  },

  {
    questionRus: "Сколько тебе лет?",
    questionGerm: "_ alt bist du?",
    v1: "Wann",
    v2: "Wie",
    v3: "Wo",
    v4: "Wer",
    answer: "Wie",
  },
  {
    questionRus: "Какое у тебя хобби?",
    questionGerm: "_ ist dein Hobby?",
    v1: "Wie",
    v2: "Wann",
    v3: "Was",
    v4: "Wo",
    answer: "Was",
  },
  {
    questionRus: "Где находится музей?",
    questionGerm: "_ befindet sich das Museum?",
    v1: "Wann",
    v2: "Wo",
    v3: "Was",
    v4: "Wie",
    answer: "Wo",
  },
  {
    questionRus: "Какой день недели сегодня?",
    questionGerm: "_ Tag ist heute?",
    v1: "Wo",
    v2: "Wann",
    v3: "Welcher",
    v4: "Wie",
    answer: "Welcher",
  },
  {
    questionRus: "Какие языки ты говоришь?",
    questionGerm: "_ Sprachen sprichst du?",
    v1: "Wie",
    v2: "Wo",
    v3: "Was",
    v4: "Welche",
    answer: "Welche",
  },
  {
    questionRus: "Кто пришёл сегодня на встречу?",
    questionGerm: "_ ist heute zum Treffen gekommen?",
    v1: "Wo",
    v2: "Wann",
    v3: "Was",
    v4: "Wer",
    answer: "Wer",
  },

  {
    questionRus: "Какой цвет у неба?",
    questionGerm: "_ Farbe hat der Himmel?",
    v1: "Wann",
    v2: "Welche",
    v3: "Wo",
    v4: "Wie",
    answer: "Welche",
  },
  {
    questionRus: "Какое животное у вас есть?",
    questionGerm: "_ Tier hast du?",
    v1: "Wie",
    v2: "Wo",
    v3: "Welches",
    v4: "Was",
    answer: "Welches",
  },
  {
    questionRus: "Какая ваша любимая книга?",
    questionGerm: "_ Buch ist dein Lieblingsbuch?",
    v1: "Wie",
    v2: "Was",
    v3: "Wo",
    v4: "Welches",
    answer: "Welches",
  },

  {
    questionRus: "Сколько времени?",
    questionGerm: "_ spät ist es?",
    v1: "Wann",
    v2: "Wie",
    v3: "Welche",
    v4: "Was",
    answer: "Wie",
  },
  {
    questionRus: "Как выглядит ваша мама?",
    questionGerm: "_ sieht deine Mutter aus?",
    v1: "Wann",
    v2: "Wie",
    v3: "Welche",
    v4: "Was",
    answer: "Wie",
  },
  {
    questionRus: "Куда вы идете?",
    questionGerm: "_ gehst du?",
    v1: "Wie",
    v2: "Wohin",
    v3: "Welche",
    v4: "Was",
    answer: "Wohin",
  },
  {
    questionRus: "Почему ты счастлив?",
    questionGerm: "_ bist du glücklich?",
    v1: "Wann",
    v2: "Wie",
    v3: "Warum",
    v4: "Was",
    answer: "Warum",
  },
  {
    questionRus: "Что вы хотите сделать?",
    questionGerm: "_ möchtest du machen?",
    v1: "Wann",
    v2: "Wie",
    v3: "Welche",
    v4: "Was",
    answer: "Was",
  },
  {
    questionRus: "Кто ваш лучший друг?",
    questionGerm: "_ ist dein bester Freund?",
    v1: "Wann",
    v2: "Wie",
    v3: "Wer",
    v4: "Was",
    answer: "Wer",
  },

  {
    questionRus: "Сколько братьев или сестер у вас есть?",
    questionGerm: "_ viele Geschwister hast du?",
    v1: "Wann",
    v2: "Wie",
    v3: "Welche",
    v4: "Was",
    answer: "Wie",
  },
  {
    questionRus: "Какая ваша любимая еда?",
    questionGerm: "_ ist dein Lieblingsessen?",
    v1: "Wann",
    v2: "Wie",
    v3: "Was",
    v4: "Welche",
    answer: "Was",
  },
  {
    questionRus: "Какой ваш любимый фильм?",
    questionGerm: "_ ist dein Lieblingsfilm?",
    v1: "Wann",
    v2: "Wie",
    v3: "Welcher",
    v4: "Was",
    answer: "Was",
  },
  {
    questionRus: "Какой ваш любимый предмет в школе?",
    questionGerm: "_ ist dein Lieblingsfach in der Schule?",
    v1: "Wann",
    v2: "Wie",
    v3: "Was",
    v4: "Welches",
    answer: "Was",
  },
  {
    questionRus: "Когда у вас день рождения?",
    questionGerm: "_ hast du Geburtstag?",
    v1: "Wie",
    v2: "Wann",
    v3: "Was",
    v4: "Welcher",
    answer: "Wann",
  },
  {
    questionRus: "Как вы проводите выходные?",
    questionGerm: "_ verbringst du das Wochenende?",
    v1: "Wann",
    v2: "Wie",
    v3: "Welcher",
    v4: "Was",
    answer: "Wie",
  },


  {
    questionRus: "Как вы отмечаете Новый год?",
    questionGerm: "_ feierst du Silvester?",
    v1: "Wie",
    v2: "Wann",
    v3: "Was",
    v4: "Welche",
    answer: "Wie",
  },
  {
    questionRus: "Какой ваш любимый вид спорта?",
    questionGerm: "_ ist deine Lieblingssportart?",
    v1: "Wie",
    v2: "Was",
    v3: "Wann",
    v4: "Welche",
    answer: "Was",
  },
  {
    questionRus: "Как вы проводите летние каникулы?",
    questionGerm: "_ verbringst du die Sommerferien?",
    v1: "Wie",
    v2: "Was",
    v3: "Wann",
    v4: "Welche",
    answer: "Wie",
  },
  {
    questionRus: "Как вы учите иностранные языки?",
    questionGerm: "_ lernst du Fremdsprachen?",
    v1: "Wie",
    v2: "Was",
    v3: "Wann",
    v4: "Welche",
    answer: "Wie",
  },
  {
    questionRus: "Как вы предпочитаете путешествовать: на машине или на поезде?",
    questionGerm: "_ reist du lieber: mit dem Auto oder mit dem Zug?",
    v1: "Wie",
    v2: "Was",
    v3: "Welche",
    v4: "Wann",
    answer: "Wie",
  },
  {
    questionRus: "Как вы отдыхаете после тяжелого дня?",
    questionGerm: "_ entspannst du dich nach einem schweren Tag?",
    v1: "Wie",
    v2: "Wann",
    v3: "Was",
    v4: "Welche",
    answer: "Wie",
  },
]

}

shuffleArray(questions.questions)
  
  export default questions;